### ISSUE TITLE
Chinese .msg is garbled

### ISSUE THREAD

**Issue by whaozl** [bbottema/msgparser#2]
This has this probolem https://github.com/bbottema/outlook-message-parser/issues/3

**Comment by bbottema** [comment]
Looking into it at bbottema/outlook-message-parser#3

**Comment by bbottema** [comment]
I got confused. I'm able to close issues in your fork? Strange...

**Comment by whaozl** [comment]
@bbottema 
Thank you so much, I don't know how to thank. I also hope that msgparser will not be garbled.
